source 'https://rubygems.org'
ruby '2.7.1'

gem 'sinatra', '~> 2.1.0'
gem 'sinatra-cross_origin'
gem 'contentful'
gem 'puma', '3.12.1'
gem 'rake'

group :test do
  gem 'rack-test'
  gem 'rspec'
  gem 'vcr'
  gem 'webmock'
end

group :development, :test do
  gem 'pry-byebug'
  gem 'shotgun'
end