swagger: "2.0"
info:
  description: "This is a sample recipe server."
  version: "1.0.0"
  title: "Recipes"
host: "localhost:4567"
basePath: "/api/v1"
tags:
- name: "recipe"
  description: "Everything about your recipe"
schemes:
- "http"
paths:
  /recipes:
    get:
      tags:
      - "recipe"
      summary: "Get all recipes"
      description: ""
      operationId: "getRecipes"
      produces:
      - "application/json"
      responses:
        "200":
          description: "List of recipes"
          schema:
            $ref: "#/definitions/Recipes"
  /recipes/{recipeId}:
    get:
      tags:
      - "recipe"
      summary: "Finds recipe by id"
      operationId: "getRecipeById"
      produces:
      - "application/json"
      parameters:
      - name: "recipeId"
        in: "path"
        description: "ID of recipe to return"
        required: true
        type: string
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Recipe"
        "404":
          description: "Recipe not found"
definitions:
  Recipes:
    type: "array"
    items:
      type: "object"
      properties:
        id:
          type: "string"
        title:
          type: "string"
        image:
          type: "string"
  Chef:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
    xml:
      name: "Category"

  Recipe:
    type: "object"
    required:
    - "id"
    - "title"
    - "image"
    - "tags"
    - "description"
    - "chef"
    properties:
      id:
        type: "string"
      chef:
        $ref: "#/definitions/Chef"
      title:
        type: "string"
        example: "recipe_1"
      tags:
        type: "array"
        items:
          type: "string"
      description:
        type: "string"
        example: "description"
      image:
        type: "string"
        example: "/images.de/link"
